# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Document\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            mongodb:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~
            
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            provider: our_db_provider
            user_checker: AppBundle\Security\UserChecker
            
            form_login:
                login_path: login
                check_path: login
                default_target_path: applicationAdmin

            access_denied_handler: AppBundle\Security\AccessDeniedHandler

            logout:
                path:   /logout
                target: /login

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin', roles: ROLE_ADMIN }
